config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout

  get 'search' => 'search#search'

  resources :customers, only: [:index] do
    get 'tasks', on: :member
    get 'contacts', on: :member
  end

  resources :contacts, only: [:show]
  resources :tasks, only: [:show]

  root 'static_pages#home'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include Searchable
  searchable_fields :firstname, :lastname

  belongs_to :customer
  belongs_to :country
  has_many :tasks

  default_scope { order('LOWER(lastname) ASC') } 
end

app/models/country.rb
class Country < ActiveRecord::Base
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include Searchable
  searchable_fields :custname, :city, :region

  has_many :contacts
  has_one :country
  has_many :tasks

  default_scope { order('LOWER(custname) ASC') } 
end

app/models/task.rb
class Task < ActiveRecord::Base
  include Searchable
  searchable_fields :tasktitle, :description

  belongs_to :customer
  belongs_to :contact
  has_many :workrecords

  default_scope { order('entrydate DESC') } 
end

app/models/technician.rb
class Technician < ActiveRecord::Base
  has_many :workrecords
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |u|
      u.provider = auth["provider"]
      u.uid = auth["uid"]
      u.first_name = auth["info"]["first_name"]
      u.last_name = auth["info"]["last_name"]
    end
  end

end

app/models/workentry.rb
class Workentry < ActiveRecord::Base
  include Searchable
  searchable_fields :internal_notes, :summary_notes

  belongs_to :workrecord

  

  def task
    workrecord.task
  end

  def technician
    workrecord.technician
  end
end

app/models/workrecord.rb
class Workrecord < ActiveRecord::Base
  belongs_to :task
  belongs_to :technician
  has_many :workentries

  default_scope { order('entrytimestamp DESC') } 

  # little aliasing so we're not typing workentries.first all the time
  def e
    if workentries.any?
      workentries.first
    else
      nil
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact = Contact.find_by_id(params[:id])
    @tasks = @contact.tasks.paginate(page: params[:page])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    if char = params[:char]
      @customers = Customer.where('custname ILIKE ?', "#{char}%")
                           .paginate(page: params[:page])
    else
      @customers = Customer.all.paginate(page: params[:page])
    end
  end

  def tasks
    @customer = Customer.find_by_id(params[:id])
    @tasks = @customer.tasks.paginate(page: params[:page])
    render :show
  end

  def contacts
    @customer = Customer.find_by_id(params[:id])
    @contacts = @customer.contacts.paginate(page: params[:page])
    render :show
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @search_term = params[:q] # used in view
    @search_type = params[:type]    

    if !@search_term || @search_term.length < 1
      flash[:warning] = 
        "Please enter a longer search term"
      redirect_to_back
    else  
      # TODO - figure out searching tasks within contacts and customer
      
      # Defaults to entry/notes search, if type param is set will search contact,
      # customer, or ticket title/description
      if @search_type == "contacts"
        @contacts = Contact.search(@search_term).paginate(page: params[:page])
      elsif @search_type == "customers"
        @customers = Customer.search(@search_term).paginate(page: params[:page])
      elsif @search_type == "tasks"
        @tasks = Task.search(@search_term).order(entrydate: :desc)
                     .paginate(page: params[:page])
      else
        @workentries = Workentry.search(@search_term).order(entrytimestamp: :desc)
                                .paginate(page: params[:page])
      end
    end
  end

end

# TODO - make gist of this, showing WillPaginate:Collection usage
# @tasks = Task.search(@search_term).order(entrydate: :desc)
#   @workentries = Workentry.search(@search_term).order(entrytimestamp: :desc)
#   @tasks_and_entries_all = @tasks + @workentries
#
#   custom pagination needed due to heterogeneous tasks and entries collection
#   current_page = (params[:page] || 1).to_i
#   per_page = 20
#   @tasks_and_entries = WillPaginate::Collection.create(current_page, per_page, @tasks_and_entries_all.length) do |pager|
#     start = (current_page-1) * per_page # assuming current_page is 1 based.
#     pager.replace(@tasks_and_entries_all[start, per_page])
# end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  skip_before_action :authenticate_user!

  def create
    #raise request.env['omniauth.auth'].to_yaml
    auth = request.env['omniauth.auth']

    # check for correct group membership
    if auth.extra.raw_info.id_token_claims.groups.include?(ENV['AZURE_GROUP_ID'])
      user = User.find_by_uid(auth["uid"]) || User.create_with_omniauth(auth)
      session[:user_id] = user.id

      flash[:success] = "Signed in!"
      redirect_to customers_path
    else
      flash[:warning] = "Cannot sign you in, check Azure group membership!"
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # def index
  #   @tasks = find_parent.tasks
  # end

  def show
    @task = Task.find_by_id(params[:id])
    @workrecords = @task.workrecords.includes(:workentries)
  end

  private

  # def find_parent
  #   @parent ||=
  #     if params[:customer_id]
  #       Customer.find_by_id(params[:customer_id])
  #     elsif params[:contact_id]
  #       Contact.find_by_id(params[:contact_id])
  #     end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def trim_and_highlight(text, search_term)
    preview_chars = 300
    search_term = sanitize(search_term)

    if index = text.index(/#{search_term}/i)
      trim = search_term.length + preview_chars
      start = index - trim >= 0 ? index - trim : 0
      if start <= 3
        result = "#{text[start..(index + trim)]}..."
      else
        result = "...#{text[start..(index + trim)]}..."
      end
    else
      result = "#{text[0..preview_chars]}..."
    end
    highlight(simple_format(result.html_safe), search_term)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>F1 Ticket Archive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'public', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "shared/navbar" %>

<div class="container">

  <div class="row">
    
    <%= render partial: "shared/flash" %>
    
    <%= yield %>
    
  </div>
</div>

</body>
</html>

app/views/shared/_contacts.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="alert alert-info">
      Click on the name of the contact to view all tickets assigned to them.
    </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
    </tr>
  </thead>
  <tbody>

    <% @contacts.each do |c| %>
      <tr>
        <td>
          <%= link_to "#{c.firstname.titleize} #{c.lastname.titleize}", contact_path(c.id) %> 
        </td>
        <td>
          <%= c.city %> 
        </td>
        <td>
          <%= c.state %> 
        </td> 
      </tr>
    <% end %>

  </tbody>
</table>

app/views/shared/_customers.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>City</th>
      <th>State</th>
    </tr>
  </thead>
  <tbody>

    <% @customers.each do |c| %>
      <tr>
        <td>
          <%= link_to c.custname, tasks_customer_path(c.id) %> 
        </td>
        <td>
          <%= c.city %> 
        </td>
        <td>
          <%= c.region %> 
        </td> 
      </tr>
    <% end %>

  </tbody>
</table>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>

  <div class="alert alert-<%= type %> alert-dismissible" role="alert">

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

    <%= message %>

  </div>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, {class: "navbar-brand"} do %>
        <span><%= image_tag "archive.png" %></span>
        F1 Ticket Archive
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        
        <p class="navbar-text navbar-right">
          Howdy, <%= current_user.first_name %>! | 
          <%= link_to "Sign out?", signout_path %>
        </p>  

        <ul class="nav navbar-nav">
          <li class="<%= current_page?(customers_path) ? 'active' : nil %>">
            <%= link_to "Customer List", customers_path %>
          </li>
        </ul>
        <form action="<%= search_path %>" method="get" class="navbar-form navbar-left" role="search">        
          <div class="form-group">
            <div class="input-group search-bar">
              <input name="type" type="hidden" value="<%= @search_type %>">
              <%= text_field_tag :q, params[:q], class: "form-control", placeholder:"Search" %>
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <i class="fa fa-search" aria-hidden="true"></i>
                  <span class="sr-only">Search</span>
                </button>
              </span>
            </div>
          </div>
        </form>

      <% else %>

        <p class="navbar-text navbar-right">
          <%= link_to "Sign in!", "/auth/azureactivedirectory"  %>
        </p>  
        
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div> <!-- /.container -->
</nav>

app/views/shared/_tasks.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Autotask Ticket</th>
      <th>Title</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>

    <% @tasks.each do |t| %>
      <tr>
        <td>
          <%= link_to t.tnumber, task_path(t.id) %> 
        </td>
        <td>
          <%= t.tasktitle %> 
        </td>
        <td>
          <%= t.entrydate.strftime("%m/%d/%Y") %> 
        </td> 
      </tr>
    <% end %>

  </tbody>
</table>