config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout

  get 'search' => 'search#search'

  resources :customers, only: [:index] do
    get 'tasks', on: :member
    get 'contacts', on: :member
  end

  resources :contacts, only: [:show]
  resources :tasks, only: [:show]

  root 'static_pages#home'

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include Searchable
  searchable_fields :custname, :city, :region

  has_many :contacts
  has_one :country
  has_many :tasks

  default_scope { order('LOWER(custname) ASC') } 
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    if char = params[:char]
      @customers = Customer.where('custname ILIKE ?', "#{char}%")
                           .paginate(page: params[:page])
    else
      @customers = Customer.all.paginate(page: params[:page])
    end
  end

  def tasks
    @customer = Customer.find_by_id(params[:id])
    @tasks = @customer.tasks.paginate(page: params[:page])
    render :show
  end

  def contacts
    @customer = Customer.find_by_id(params[:id])
    @contacts = @customer.contacts.paginate(page: params[:page])
    render :show
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.erb
<div class="alert alert-info">
  Welcome to the F1 Ticket Archive.  Below is a list of all customers, you can click to view tickets and contacts for that customer.  You can also search for a customer, contact, or ticket notes from the top bar.
</div>

<div class="text-center">
  <ul class="pagination">
    <li class="disabled">
      <span>
        Filter by Name
      </span>
    </li>
    <% unless params[:char] %>
      <li class="active">  
        <span>All</span>
      </li>
    <% else %>
      <li>
        <%= link_to "All", customers_path  %>
      </li>
    <% end %>

    <% ('A'..'Z').each do |char| %>
         <% if char==params[:char] %>
              <li class="active">  
                <span><%= char %></span>
              </li>
         <% else %>
              <li>
                <%= link_to char, customers_path(char: char) %>
              </li>
         <% end %>
    <% end %>
  </ul>
</div>

<%= render partial: "shared/customers", locals: {customers: @customers} %>

<div class="text-center">
  <%= will_paginate @customers, renderer: BootstrapPagination::Rails %>
</div>

app/views/customers/show.html.erb
<div class="col-sm-10">
 <h3 class="cust-page-heading">
   <%= @customer.custname %>
 </h3>
 <address>
   <%= @customer.city %>, <%= @customer.region %>
 </address>
</div>

<div class="col-sm-2">
  <ul class="nav nav-pills">
    <li role="presentation" class="<%= current_page?(tasks_customer_path(@customer.id)) ? "active" : nil %>">
      <%= link_to "Tickets", tasks_customer_path(@customer.id) %>  
    </li>
    <li role="presentation" class="<%= current_page?(contacts_customer_path(@customer.id)) ? "active" : nil %>">
      <%= link_to "Contacts", contacts_customer_path(@customer.id) %>  
    </li>
  </ul>
</div>


<div class="col-sm-12"> 
  <% if @tasks %>
    <% if @tasks.any? %>
      <%= render partial: "shared/tasks", locals: {tasks: @tasks} %>
      <div class="text-center">
        <%= will_paginate @tasks, renderer: BootstrapPagination::Rails %>
      </div>
    <% else %>
      <h3 class="text-center">No Tickets to display!</h3>
    <% end %>

  <% elsif @contacts %>
    <% if @contacts.any? %>  
      <%= render partial: "shared/contacts", locals: {contacts: @contacts} %>
      <div class="text-center">
        <%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
      </div>
    <% else %>
      <h3 class="text-center">No Contacts to display!</h3>
    <% end %>
  <% end %>
</div>